### ISSUE TITLE
Update submodules for docs

### ISSUE THREAD

**Issue by aaronmgdr** [valora-inc/docs#980]
the submodules commits are out of date as such they show incorrect information such as the recommendation to use react-celo. 👎

https://github.com/valora-inc/docs/tree/main/submodules

**Comment by jeanregisser** [comment]
Woops, the automation got stuck. Fixed in #686.

Now it says we recommend https://github.com/celo-org/rainbowkit-celo, but this should be changed once I can get Valora added directly to RainbowKit.
